baseURL = ""
languageCode = "en-us"
title = "Kevin Selwyn"
theme = "flex"

pygmentsCodefences = true
pygmentsUseClassic = false
pygmentsUseClasses = true

[params]
gaTrackingCode = "UA-23140413-1"
footer = ""

[menu]
[[menu.nav]]
name = "Resume"
url = "resume/"
weight = 1

[[menu.nav]]
name = "Posts"
url = "posts/"
weight = 2

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.nav]]
name = "Categories"
url = "categories/"
weight = 4

[markup.goldmark.renderer]
unsafe= true
