baseURL = ""
languageCode = "en-us"
title = "Kevin Selwyn"
theme = "flex"

[params]
footer = ""

[menu]
[[menu.nav]]
name = "Posts"
url = "posts/"
weight = 1

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 2

[[menu.nav]]
name = "Categories"
url = "categories/"
weight = 3
